# Generated by tools/make_registry.py from setup.py's FAMILIES, MODELS and HF_REVISIONS.
# Do not edit by hand: run `python3 tools/make_registry.py` (the drift check fails otherwise).
{
  "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF" = {
    family = "coder";
    name = "qwen3.8-flash-next-coder";
    revision = "5348543e0147355ac9cbcb031184a3546350988e";
    subdir = "{q}/";
    file = "Qwen3.8-Flash-Next-GSQ-RCO-{q}-0000{i}-of-00002.gguf";
    profile = "expert-profile-coder.bin";
    packArgs = [ ];
    trainedContext = 262144;
    mmproj = {
      repo = "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF";
      file = "mmproj-Qwen3.8-Flash-Next-BF16.gguf";
    };
    quants = {
      "IQ1_M" = {
        shards = 2;
        downloadGb = 58.4;
        vision = true;
        experimental = false;
      };
    };
  };
  "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF" = {
    family = "qwen";
    name = "qwen3.8-flash-next";
    revision = "ed59f92082b1e93c0e96d60a8b11aab089b52f09";
    subdir = "{q}/";
    file = "Qwen3.8-Flash-Next-GSQ-RCO-{q}-0000{i}-of-00002.gguf";
    profile = null;
    packArgs = [ ];
    trainedContext = 262144;
    mmproj = {
      repo = "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF";
      file = "mmproj-Qwen3.8-Flash-Next-BF16.gguf";
    };
    quants = {
      "IQ2_XS" = {
        shards = 2;
        downloadGb = 68.0;
        vision = true;
        experimental = false;
      };
      "IQ3_S" = {
        shards = 2;
        downloadGb = 83.6;
        vision = true;
        experimental = false;
      };
      "IQ3_XXS" = {
        shards = 2;
        downloadGb = 75.8;
        vision = true;
        experimental = false;
      };
      "Q2_0" = {
        shards = 2;
        downloadGb = 66.4;
        vision = true;
        experimental = false;
      };
    };
  };
  "ukisai/Swift-1.5-Qwen3.8-Flash-Next-GSQ-RCO-GGUF" = {
    family = "swift";
    name = "swift-1.5";
    revision = "b22d729eae29b5796f76fb70f91aef549b9fc52c";
    subdir = null;
    file = "Swift-Qwen3.8-Flash-Next-GSQ-RCO-{q}-0000{i}-of-00002.gguf";
    profile = null;
    packArgs = [ ];
    trainedContext = 262144;
    mmproj = {
      repo = "ukisai/Swift-1.5-Qwen3.8-Flash-Next-GSQ-RCO-GGUF";
      file = "mmproj-Swift-Qwen3.8-Flash-Next-BF16.gguf";
    };
    quants = {
      "IQ2_XS" = {
        shards = 2;
        downloadGb = 68.0;
        vision = true;
        experimental = false;
      };
      "IQ3_XXS" = {
        shards = 2;
        downloadGb = 75.8;
        vision = true;
        experimental = false;
      };
    };
  };
  "unsloth/Qwen3.8-Flash-Next-GGUF" = {
    family = "unsloth";
    name = "qwen3.8-flash-next-unsloth";
    revision = "38bb39ee97821de2c9009abb7e93950eec396e66";
    subdir = "{q}/";
    file = "Qwen3.8-Flash-Next-{q}-0000{i}-of-00004.gguf";
    profile = null;
    packArgs = [ "--compat-bf16" ];
    trainedContext = 262144;
    mmproj = {
      repo = "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF";
      file = "mmproj-Qwen3.8-Flash-Next-BF16.gguf";
    };
    quants = {
      "UD-IQ4_XS" = {
        shards = 3;
        downloadGb = 93.7;
        vision = true;
        experimental = false;
        file = "Qwen3.8-Flash-Next-{q}-0000{i}-of-00003.gguf";
      };
      "UD-Q4_K_XL" = {
        shards = 4;
        downloadGb = 111.3;
        vision = false;
        experimental = true;
      };
    };
  };
}
